---
name: "Setup Matrix and Armory"

description: "Install Armory"


runs:
  using: "composite"
  steps:
    - name: 🐄 Got git?
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 📩 Checkout the Source
      run: |
        git fetch --prune --unshallow || true
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        # Verify .git folder
        if [ ! -d "./.git" ]; then
          echo "Expected ./.git folder to exist"
          exit 1
        fi

    - name: 🐍 Use Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: 🌱 Setup Test Enviroment
      run: |
        python -m pip install --upgrade pip

    - name: ⚙️ Installing Armory
      shell: bash
      run: |
        pip install --no-compile --editable '.[developer]'
        armory configure --use-defaults
        # pip install --no-compile --editable '.[developer,engine,math,datasets,pytorch]'

    - uses: actions/cache@v2
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

    - name: ⚙️ Installing Armory
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install --no-compile --editable '.[developer]'
        armory configure --use-defaults
      # pip install --no-compile --editable '.[developer,engine,math,datasets,pytorch]'
