ARG base_image_tag
ARG armory_version
ARG armory_build_type


FROM twosixarmory/base:${base_image_tag} AS armory-local

WORKDIR /armory-repo

COPY pyproject.toml setup.py pytest.ini /armory-repo/
COPY ./.git /armory-repo/.git
COPY ./armory /armory-repo/armory/
COPY ./tests /armory-repo/tests/
COPY ./scenario_configs /armory-repo/scenario_configs/

RUN echo "Installing ART" && \
    pip install --no-cache-dir adversarial-robustness-toolbox==1.10.3 && \

    echo "Updating Base Image"            && \
    pip install hatch hatch-vcs           && \
    python -m pip install --upgrade pip   && \

    echo "Building Armory from local source" && \
    # Currently ALL versioning methods rely on the `.git` directory being
    # present. Alternatively, one could patch `pyproject.toml` to use
    # `__about__.py` in the local armory directory.
    # sed -i 's/source = "vcs"/#source = "vcs"/g' pyproject.toml  && \
    pip install --no-cache-dir --no-compile '.[host]' && \
    armory configure --use-default

WORKDIR /workspace

