ARG base_image_tag

FROM twosixarmory/base:${base_image_tag} AS armory-local

WORKDIR /armory-repo

# NOTE: This COPY command is filtered using the `.dockerignore` file
#       in the root of the repo.
COPY ./ /armory-repo

RUN pip install git+https://github.com/romesco/hydra-lightning/\#subdirectory=hydra-configs-pytorch-lightning

RUN echo "Building Armory from local source"                                            && \
    echo "Updating Base Image..."                                                       && \
      python -m pip install --upgrade pip                                               && \
    echo "Installing Armory..."                                                         && \
      pip install --no-compile --no-cache-dir --editable '.[engine,deepspeech,jupyter]' && \
    echo "Configuring Armory..."                                                        && \
      armory configure --use-default                                                    && \
    echo "Cleaning up..."                                                               && \
      rm -rf /armory-repo/.git

WORKDIR /workspace


# ------------------------------------------------------------------
# DEVELOPER NOTES:
# ------------------------------------------------------------------
#  - pytorch-lightning >= 1.5.0 will break Deep Speech 2
#  - torchmetrics >= 0.8.0 will break pytorch-lightning 1.4
#  - hydra-lightning installs omegaconf
#  - google-cloud-storage needed for checkpoint.py import
#  - only sox python bindings are installed; underlying sox binaries not needed

# NOTE: Listed dependencies of PyTorch Deep Speech 2, but do not appear
#       to be used for inference (only for training), they are not installed:
#         - torchelastic
#         - wget
#         - flask
#         - fairscale
# ------------------------------------------------------------------
