##########################################################################################
#
#                           ARMORY Baseline Docker Image
#
# This File contains the baseline image for Armory docker images.  All framework
# based images should inhereit from this image using:
#       FROM twosixlabs/armory-baseline AS armory-baseline
#
##########################################################################################

FROM nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04

ENV PATH=/opt/mamba/bin:$PATH
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/mamba/bin

WORKDIR /armory-repo/

COPY environment.yml /armory-repo/

# Basic Apt-get Bits
RUN apt-get -y -qq update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
    wget \
    vim \
    build-essential \
    git \
    curl \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libarchive13 \
    libcairo2 \
    && rm -rf /var/lib/apt/lists/*
# libgl1-mesa-glx is needed for cv2 (opencv-python)
# libarchive13 is needed for mamba

RUN curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh" && \
    /bin/bash Mambaforge-$(uname)-$(uname -m).sh -b -p /opt/mamba && \
    rm Mambaforge-$(uname)-$(uname -m).sh && \
    mamba update mamba && \
    mamba update -n base -c defaults conda && \
    mamba env update -n base -f environment.yml

WORKDIR /workspace
