ARG base_image_tag

FROM twosixarmory/base:${base_image_tag} AS armory-local

WORKDIR /armory-repo

# NOTE: This COPY command is filtered using the `.dockerignore` file
#       in the root of the repo.
COPY ./ /armory-repo

RUN echo "Updating pip" && \
    pip install --upgrade pip && \
    echo "Building Armory from local source" && \
    pip install --no-compile --no-cache-dir --editable '.[engine,pytorch,jupyter]' && \
    echo "Configuring Armory..." && \
    armory configure --use-default && \
    echo "Cleaning up..." && \
    rm -rf /armory-repo/.git

WORKDIR /workspace
