ARG base_image_tag
ARG armory_version
ARG armory_build_type


FROM twosixarmory/base:${base_image_tag} AS armory-local

COPY dist /tmp

WORKDIR /armory-repo

RUN echo "Installing ART"                                               ; \
    pip install --no-cache-dir adversarial-robustness-toolbox==1.10.3   ; \
    echo "Building Armory from local source"                            ; \
    echo "Updating Base Image..."                                       ; \
      python -m pip install --upgrade pip                               ; \
    echo "Unpacking sdist into `/armory-repo`..."                       ; \
      tar -zxvf /tmp/*.tar.gz                                             \
         --strip-components=1                                             \
         --directory /armory-repo                                       ; \
    echo "Installing Armory..."                                         ; \
      pip install --no-compile --no-cache-dir --editable '.[host]'      ; \
    echo "Configuring Armory..."                                        ; \
      armory configure --use-default                                    ; \
    echo "Cleaning up..."                                               ; \
      rm -rf /tmp/*

WORKDIR /workspace
