ARG base_image_tag

FROM twosixarmory/pytorch:${base_image_tag} AS armory-bytetrack

RUN pip install --no-cache-dir \
    git+https://github.com/ifzhang/ByteTrack.git \
    thop \
    lap \
    Cython

# Requires cython for install, so will fail if run in the same pip install as cython
RUN pip install --no-cache-dir \
    cython-bbox

WORKDIR /workspace
