# More details on the pytorchyolo installation can be found here:
# https://github.com/eriklindernoren/PyTorch-YOLOv3

ARG base_image_tag

FROM twosixarmory/base:${base_image_tag} AS armory-local

WORKDIR /armory-repo

# NOTE: This COPY command is filtered using the `.dockerignore` file
#       in the root of the repo.
COPY ./ /armory-repo


RUN echo "Building Armory from local source"                         && \
    echo "Updating Base Image..."                                    && \
      python -m pip install --upgrade pip                            && \
    echo "Installing Armory..."                                      && \
      pip install --no-compile --no-cache-dir --editable '.[yolo]'   && \
    echo "Configuring Armory..."                                     && \
      armory configure --use-default                                 && \
    echo "Cleaning up..."                                            && \
      rm -rf /armory-repo/.git


## Tensorflow Patches
#  see: https://github.com/tensorflow/tensorflow/issues/56927
#  see: https://github.com/keras-team/keras/issues/17422#issuecomment-1539388368
ENV CONDA_PREFIX=/opt/conda
ENV XLA_FLAGS=--xla_gpu_cuda_data_dir=$CONDA_PREFIX/lib/

RUN echo "Applying TensorFlow patches" && \
    mamba install -c nvidia cuda-nvcc=11.3.58 && \
    mkdir -p $CONDA_PREFIX/etc/conda/activate.d && \
    mkdir -p $CONDA_PREFIX/lib/nvvm/libdevice && \
    cp $CONDA_PREFIX/lib/libdevice.10.bc $CONDA_PREFIX/lib/nvvm/libdevice/


WORKDIR /workspace
